name: Check PTT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pentest
        uses: pentesttoolscom/pentesttools-github-action@master
        id: ptt
        with:
          target: https://preprod.stage.griddynamics.net

      - name: Check Pentest results
        run: |
          echo "The report: ${{ steps.ptt.outputs.result }}"
