name: Test PTT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Pentest
        uses: pentesttoolscom/pentesttools-github-action@v0.0.4-alpha
        id: ptt
        with:
          target: https://preprod.stage.griddynamics.net
          format: text
          fail: none
          type: light
          max_scan_time: 10

      - name: Check Pentest results
        run: |
          echo "The report: ${{ steps.ptt.outputs.result }}"
